### ISSUE TITLE
package dicoverability

### ISSUE THREAD

**Issue by nsajko** [jverzani/AMRVW.jl#17]
Doing a JuliaHub package search for "polynomial roots" or "polynomial zeros" should turn up this package. I only found this package because it's mentioned in the Polynomials.jl docs.

**Comment by nsajko** [comment]
I think maybe you can edit some kind of description somewhere to include words like "polynomial roots".

**Comment by jverzani** [comment]
THanks. I've updated the readme, which I think picks up the description. But if you have other suggestions, I'd happily implement.

**Comment by jverzani** [comment]
That search feature on Julia hub could use some improvement in its choice of defaults, which seem to match on package name, not on package features. Anyways, going to close this, but reopen if you have any other suggestions.
